export const DOC_CATEGORIES = [
  { id: 'rental', title: 'Rental & Housing', titleHi: 'किराया और आवास' },
  { id: 'business', title: 'Business & Finance', titleHi: 'व्यापार और वित्त' },
  { id: 'personal', title: 'Personal & Family', titleHi: 'व्यक्तिगत और परिवार' },
  { id: 'legal', title: 'Legal Notices', titleHi: 'कानूनी नोटिस' },
  { id: 'employment', title: 'Employment', titleHi: 'रोज़गार' },
  { id: 'gov', title: 'Government', titleHi: 'सरकारी' },
];

export const DOCUMENTS = {
  // Rental & Housing
  'rent-agreement':  { category: 'rental',     name: 'Rent Agreement',            nameHi: 'किरायानामा',                  price: 199, fields: ['landlord_name', 'landlord_address', 'tenant_name', 'tenant_address', 'property_address', 'monthly_rent', 'deposit_amount', 'start_date', 'duration_months', 'state'] },
  'leave-license':   { category: 'rental',     name: 'Leave & License',           nameHi: 'लीव एंड लाइसेंस',             price: 199, fields: ['licensor_name', 'licensee_name', 'property_address', 'monthly_fee', 'deposit', 'duration_months'] },
  'noc-letter':      { category: 'rental',     name: 'NOC Letter',                nameHi: 'अनापत्ति प्रमाण पत्र (NOC)',  price: 99,  fields: ['issuer_name', 'recipient_name', 'property_details', 'purpose', 'date'] },
  'eviction-notice': { category: 'rental',     name: 'Eviction Notice',           nameHi: 'बेदखली नोटिस',                price: 99,  fields: ['landlord_name', 'tenant_name', 'property_address', 'reason', 'vacate_by_date'] },

  // Business & Finance
  'partnership-deed':  { category: 'business', name: 'Partnership Deed',          nameHi: 'साझेदारी विलेख',              price: 499, fields: ['partner1_name', 'partner1_address', 'partner2_name', 'partner2_address', 'business_name', 'business_address', 'profit_ratio', 'start_date'] },
  'mou':               { category: 'business', name: 'MOU Agreement',             nameHi: 'समझौता ज्ञापन (MOU)',         price: 499, fields: ['party1_name', 'party2_name', 'purpose', 'effective_date', 'duration'] },
  'business-contract': { category: 'business', name: 'Business Contract',         nameHi: 'व्यापार अनुबंध',              price: 499, fields: ['party1_name', 'party1_address', 'party2_name', 'party2_address', 'scope_of_work', 'payment_terms', 'start_date', 'duration'] },
  'nda':               { category: 'business', name: 'NDA Agreement',             nameHi: 'गोपनीयता समझौता (NDA)',       price: 299, fields: ['party1_name', 'party1_company', 'party2_name', 'party2_company', 'effective_date', 'duration', 'jurisdiction'] },
  'invoice':           { category: 'business', name: 'GST Invoice',               nameHi: 'जीएसटी चालान',               price: 99,  fields: ['company_name', 'company_gstin', 'client_name', 'client_gstin', 'items_description', 'total_amount', 'date'] },

  // Personal & Family
  'affidavit':         { category: 'personal', name: 'Affidavit',                 nameHi: 'शपथ पत्र',                   price: 199, fields: ['deponent_name', 'deponent_address', 'deponent_age', 'statement_purpose', 'statement_details', 'place', 'date'] },
  'gift-deed':         { category: 'personal', name: 'Gift Deed',                 nameHi: 'उपहार विलेख',                price: 499, fields: ['donor_name', 'donee_name', 'property_description', 'relationship', 'date'] },
  'will':              { category: 'personal', name: 'Will / Testament',          nameHi: 'वसीयत',                      price: 499, fields: ['testator_name', 'testator_address', 'executor_name', 'beneficiary_details', 'date'] },
  'divorce-petition':  { category: 'personal', name: 'Divorce Petition Draft',   nameHi: 'तलाक याचिका ड्राफ्ट',        price: 499, fields: ['petitioner_name', 'respondent_name', 'marriage_date', 'grounds_for_divorce', 'children_details', 'place'] },

  // Legal Notices
  'legal-notice':      { category: 'legal',    name: 'Legal Notice',              nameHi: 'कानूनी नोटिस',               price: 299, fields: ['sender_name', 'sender_address', 'recipient_name', 'recipient_address', 'notice_subject', 'notice_details', 'demand', 'response_days'] },
  'fir-draft':         { category: 'legal',    name: 'FIR Draft',                 nameHi: 'प्राथमिकी (FIR) ड्राफ्ट',   price: 199, fields: ['complainant_name', 'incident_date', 'incident_place', 'incident_description', 'police_station'] },
  'complaint-letter':  { category: 'legal',    name: 'Complaint Letter',          nameHi: 'शिकायत पत्र',                price: 99,  fields: ['complainant_name', 'complainant_address', 'authority_name', 'complaint_subject', 'complaint_details', 'relief_sought'] },
  'rti':               { category: 'legal',    name: 'RTI Application',           nameHi: 'आरटीआई आवेदन',              price: 99,  fields: ['applicant_name', 'applicant_address', 'authority_name', 'authority_address', 'information_sought', 'date'] },

  // Employment
  'offer-letter':      { category: 'employment', name: 'Offer Letter',            nameHi: 'प्रस्ताव पत्र',              price: 99,  fields: ['company_name', 'candidate_name', 'designation', 'salary', 'joining_date', 'reporting_manager'] },
  'emp-contract':      { category: 'employment', name: 'Employment Contract',     nameHi: 'रोज़गार अनुबंध',             price: 199, fields: ['company_name', 'employee_name', 'designation', 'salary', 'probation_period', 'notice_period'] },
  'termination-letter':{ category: 'employment', name: 'Termination Letter',      nameHi: 'समाप्ति पत्र',               price: 99,  fields: ['company_name', 'employee_name', 'designation', 'termination_date', 'reason', 'notice_period'] },
  'experience-cert':   { category: 'employment', name: 'Experience Certificate',  nameHi: 'अनुभव प्रमाण पत्र',         price: 99,  fields: ['company_name', 'employee_name', 'designation', 'start_date', 'end_date', 'performance_note'] },

  // Government
  'income-cert':       { category: 'gov',      name: 'Income Certificate App',    nameHi: 'आय प्रमाण पत्र आवेदन',      price: 99,  fields: ['applicant_name', 'father_name', 'address', 'annual_income', 'purpose'] },
  'caste-cert':        { category: 'gov',      name: 'Caste Certificate App',     nameHi: 'जाति प्रमाण पत्र आवेदन',    price: 99,  fields: ['applicant_name', 'father_name', 'address', 'caste_category', 'state', 'purpose'] },
  'domicile-cert':     { category: 'gov',      name: 'Domicile Certificate App',  nameHi: 'अधिवास प्रमाण पत्र आवेदन', price: 99,  fields: ['applicant_name', 'father_name', 'address', 'years_of_residence', 'state', 'purpose'] },
  'ration-card':       { category: 'gov',      name: 'Ration Card Application',   nameHi: 'राशन कार्ड आवेदन',          price: 99,  fields: ['head_of_family', 'address', 'family_members', 'annual_income', 'state'] },
};

export const FIELD_LABELS: Record<string, { en: string; hi: string; placeholder: string }> = {
  landlord_name:         { en: 'Landlord Name',            hi: 'मकान मालिक का नाम',       placeholder: 'Rajesh Kumar' },
  landlord_address:      { en: 'Landlord Address',         hi: 'मकान मालिक का पता',       placeholder: '123, Vasant Kunj, New Delhi' },
  tenant_name:           { en: 'Tenant Name',              hi: 'किरायेदार का नाम',        placeholder: 'Amit Sharma' },
  tenant_address:        { en: 'Tenant Permanent Address', hi: 'किरायेदार का स्थायी पता', placeholder: '45, Civil Lines, Jaipur' },
  property_address:      { en: 'Property Address',         hi: 'संपत्ति का पता',          placeholder: 'Flat 4B, XYZ Apartments, Delhi' },
  monthly_rent:          { en: 'Monthly Rent (₹)',         hi: 'मासिक किराया (₹)',        placeholder: '15000' },
  deposit_amount:        { en: 'Security Deposit (₹)',     hi: 'सुरक्षा जमा (₹)',         placeholder: '30000' },
  start_date:            { en: 'Start Date',               hi: 'शुरू होने की तिथि',       placeholder: 'DD/MM/YYYY' },
  duration_months:       { en: 'Duration (Months)',        hi: 'अवधि (महीने)',            placeholder: '11' },
  state:                 { en: 'State',                    hi: 'राज्य',                   placeholder: 'Maharashtra' },
  licensor_name:         { en: 'Licensor Name',            hi: 'लाइसेंसर का नाम',        placeholder: 'Suresh Mehta' },
  licensee_name:         { en: 'Licensee Name',            hi: 'लाइसेंसी का नाम',        placeholder: 'Priya Patel' },
  monthly_fee:           { en: 'Monthly License Fee (₹)', hi: 'मासिक शुल्क (₹)',         placeholder: '20000' },
  deposit:               { en: 'Deposit Amount (₹)',       hi: 'जमा राशि (₹)',            placeholder: '40000' },
  issuer_name:           { en: 'Issuer Name',              hi: 'जारीकर्ता का नाम',       placeholder: 'Ram Singh' },
  recipient_name:        { en: 'Recipient Name',           hi: 'प्राप्तकर्ता का नाम',    placeholder: 'Mohan Verma' },
  property_details:      { en: 'Property Details',         hi: 'संपत्ति विवरण',           placeholder: 'Plot No 5, Green Park, Mumbai' },
  purpose:               { en: 'Purpose',                  hi: 'उद्देश्य',               placeholder: 'Parking / Construction / Loan' },
  date:                  { en: 'Date',                     hi: 'तारीख',                  placeholder: 'DD/MM/YYYY' },
  reason:                { en: 'Reason for Eviction',      hi: 'बेदखली का कारण',         placeholder: 'Non-payment of rent' },
  vacate_by_date:        { en: 'Vacate By Date',           hi: 'खाली करने की तिथि',      placeholder: 'DD/MM/YYYY' },
  partner1_name:         { en: 'Partner 1 Name',           hi: 'साझेदार 1 का नाम',       placeholder: 'Rohan Gupta' },
  partner1_address:      { en: 'Partner 1 Address',        hi: 'साझेदार 1 का पता',       placeholder: '12 MG Road, Bangalore' },
  partner2_name:         { en: 'Partner 2 Name',           hi: 'साझेदार 2 का नाम',       placeholder: 'Vikram Singh' },
  partner2_address:      { en: 'Partner 2 Address',        hi: 'साझेदार 2 का पता',       placeholder: '45 Park Street, Kolkata' },
  business_name:         { en: 'Business / Firm Name',     hi: 'व्यापार का नाम',         placeholder: 'TechNova Solutions LLP' },
  business_address:      { en: 'Business Address',         hi: 'व्यापार का पता',         placeholder: '8th Floor, Cyber Hub, Gurugram' },
  profit_ratio:          { en: 'Profit Ratio (e.g. 50:50)',hi: 'लाभ अनुपात',             placeholder: '60:40' },
  party1_name:           { en: 'Party 1 Name',             hi: 'पक्ष 1 का नाम',          placeholder: 'ABC Pvt Ltd' },
  party2_name:           { en: 'Party 2 Name',             hi: 'पक्ष 2 का नाम',          placeholder: 'XYZ Corp' },
  effective_date:        { en: 'Effective Date',           hi: 'प्रभावी तिथि',           placeholder: 'DD/MM/YYYY' },
  duration:              { en: 'Agreement Duration',       hi: 'समझौते की अवधि',         placeholder: '2 years' },
  party1_address:        { en: 'Party 1 Address',          hi: 'पक्ष 1 का पता',          placeholder: '101 Business Park, Delhi' },
  party2_address:        { en: 'Party 2 Address',          hi: 'पक्ष 2 का पता',          placeholder: '202 Commerce Centre, Mumbai' },
  scope_of_work:         { en: 'Scope of Work',            hi: 'कार्य का दायरा',         placeholder: 'Software development services...' },
  payment_terms:         { en: 'Payment Terms',            hi: 'भुगतान की शर्तें',       placeholder: '50% advance, 50% on delivery' },
  party1_company:        { en: 'Party 1 Company',          hi: 'पक्ष 1 की कंपनी',       placeholder: 'Innovate Tech Ltd' },
  party2_company:        { en: 'Party 2 Company',          hi: 'पक्ष 2 की कंपनी',       placeholder: 'Build Corp Pvt Ltd' },
  jurisdiction:          { en: 'Jurisdiction (City)',      hi: 'न्यायक्षेत्र (शहर)',     placeholder: 'Mumbai / Delhi / Bangalore' },
  company_name:          { en: 'Company Name',             hi: 'कंपनी का नाम',           placeholder: 'Acme Corp Pvt Ltd' },
  company_gstin:         { en: 'Company GSTIN',            hi: 'कंपनी जीएसटीआईएन',      placeholder: '27AAAPZ0114E1ZX' },
  client_name:           { en: 'Client Name',              hi: 'ग्राहक का नाम',          placeholder: 'Global Traders' },
  client_gstin:          { en: 'Client GSTIN (if any)',    hi: 'ग्राहक जीएसटीआईएन',     placeholder: '29AABCU9603R1ZX' },
  items_description:     { en: 'Items / Services',         hi: 'वस्तुएं / सेवाएं',       placeholder: 'Web development - 40 hours @ ₹2000' },
  total_amount:          { en: 'Total Amount (₹)',         hi: 'कुल राशि (₹)',            placeholder: '80000' },
  deponent_name:         { en: 'Deponent Name',            hi: 'शपथकर्ता का नाम',        placeholder: 'Suresh Verma' },
  deponent_address:      { en: 'Deponent Address',         hi: 'शपथकर्ता का पता',        placeholder: 'House No 5, Sector 12, Noida' },
  deponent_age:          { en: 'Age',                      hi: 'आयु',                    placeholder: '35' },
  statement_purpose:     { en: 'Purpose of Affidavit',     hi: 'शपथ पत्र का उद्देश्य',  placeholder: 'Address Proof / Name Change' },
  statement_details:     { en: 'Statement Details',        hi: 'बयान का विवरण',          placeholder: 'I hereby solemnly affirm and declare that...' },
  place:                 { en: 'Place',                    hi: 'स्थान',                  placeholder: 'New Delhi' },
  donor_name:            { en: 'Donor Name',               hi: 'दाता का नाम',            placeholder: 'Prakash Mehta' },
  donee_name:            { en: 'Donee Name',               hi: 'प्राप्तकर्ता का नाम',   placeholder: 'Neha Mehta' },
  property_description:  { en: 'Property Description',     hi: 'संपत्ति का विवरण',       placeholder: 'Plot No 12, Survey No 45, Pune' },
  relationship:          { en: 'Relationship',             hi: 'संबंध',                  placeholder: 'Father-Daughter / Son / Spouse' },
  testator_name:         { en: 'Testator Name',            hi: 'वसीयतकर्ता का नाम',     placeholder: 'Mahesh Sharma' },
  testator_address:      { en: 'Testator Address',         hi: 'वसीयतकर्ता का पता',     placeholder: 'Flat 7C, Shyam Nagar, Jaipur' },
  executor_name:         { en: 'Executor Name',            hi: 'निष्पादक का नाम',        placeholder: 'Ravi Sharma' },
  beneficiary_details:   { en: 'Beneficiary Details',      hi: 'लाभार्थी का विवरण',     placeholder: 'Son: Ravi Sharma (50%), Daughter: Seema Sharma (50%)' },
  petitioner_name:       { en: 'Petitioner Name',          hi: 'याचिकाकर्ता का नाम',    placeholder: 'Sunita Devi' },
  respondent_name:       { en: 'Respondent Name',          hi: 'प्रतिवादी का नाम',      placeholder: 'Anil Kumar' },
  marriage_date:         { en: 'Date of Marriage',         hi: 'विवाह की तिथि',          placeholder: 'DD/MM/YYYY' },
  grounds_for_divorce:   { en: 'Grounds for Divorce',      hi: 'तलाक के आधार',           placeholder: 'Cruelty / Desertion / Mutual Consent' },
  children_details:      { en: 'Children (if any)',        hi: 'बच्चों का विवरण',        placeholder: 'None / Name: Rahul, Age: 7' },
  sender_name:           { en: 'Sender Name',              hi: 'प्रेषक का नाम',          placeholder: 'Advocate Ramesh Kumar' },
  sender_address:        { en: 'Sender Address',           hi: 'प्रेषक का पता',          placeholder: '12/A, Lawyers Colony, Lucknow' },
  recipient_address:     { en: 'Recipient Address',        hi: 'प्राप्तकर्ता का पता',   placeholder: '7 Main Street, Varanasi' },
  notice_subject:        { en: 'Subject of Notice',        hi: 'नोटिस का विषय',          placeholder: 'Recovery of dues / Breach of contract' },
  notice_details:        { en: 'Notice Details / Facts',   hi: 'नोटिस का विवरण',         placeholder: 'Describe the facts and circumstances...' },
  demand:                { en: 'Demand / Relief Sought',   hi: 'मांग / राहत',            placeholder: 'Pay ₹50,000 within 15 days' },
  response_days:         { en: 'Response Period (Days)',   hi: 'जवाब देने की अवधि',      placeholder: '15' },
  complainant_name:      { en: 'Complainant Name',         hi: 'शिकायतकर्ता का नाम',    placeholder: 'Ritu Singh' },
  incident_date:         { en: 'Date of Incident',         hi: 'घटना की तारीख',          placeholder: 'DD/MM/YYYY' },
  incident_place:        { en: 'Place of Incident',        hi: 'घटना का स्थान',          placeholder: 'Near Railway Station, Kanpur' },
  incident_description:  { en: 'Incident Description',     hi: 'घटना का विवरण',          placeholder: 'Describe the incident in detail...' },
  police_station:        { en: 'Police Station Name',      hi: 'पुलिस स्टेशन',           placeholder: 'Kotwali Police Station, Kanpur' },
  complainant_address:   { en: 'Complainant Address',      hi: 'शिकायतकर्ता का पता',    placeholder: '45, Civil Lines, Kanpur' },
  authority_name:        { en: 'Authority / Department',   hi: 'प्राधिकरण / विभाग',     placeholder: 'Consumer Forum / RTO Office' },
  complaint_subject:     { en: 'Complaint Subject',        hi: 'शिकायत का विषय',         placeholder: 'Defective product / Service failure' },
  complaint_details:     { en: 'Complaint Details',        hi: 'शिकायत का विवरण',        placeholder: 'Describe the issue in detail...' },
  relief_sought:         { en: 'Relief Sought',            hi: 'मांगी गई राहत',          placeholder: 'Full refund / Replacement / Compensation' },
  authority_address:     { en: 'Authority Address',        hi: 'प्राधिकरण का पता',      placeholder: '5 Secretariat Rd, Bhopal' },
  information_sought:    { en: 'Information Sought',       hi: 'मांगी गई जानकारी',      placeholder: 'Details of road construction tender...' },
  candidate_name:        { en: 'Candidate Name',           hi: 'उम्मीदवार का नाम',      placeholder: 'Ankit Joshi' },
  designation:           { en: 'Designation / Role',       hi: 'पदनाम',                  placeholder: 'Software Engineer' },
  salary:                { en: 'CTC / Annual Salary (₹)',  hi: 'वार्षिक वेतन (₹)',       placeholder: '600000' },
  joining_date:          { en: 'Date of Joining',          hi: 'ज्वाइनिंग की तारीख',    placeholder: 'DD/MM/YYYY' },
  reporting_manager:     { en: 'Reporting Manager',        hi: 'रिपोर्टिंग मैनेजर',     placeholder: 'Mr. Arun Tiwari (CTO)' },
  employee_name:         { en: 'Employee Name',            hi: 'कर्मचारी का नाम',       placeholder: 'Deepak Nair' },
  probation_period:      { en: 'Probation Period',         hi: 'परिवीक्षा अवधि',        placeholder: '3 months' },
  notice_period:         { en: 'Notice Period',            hi: 'नोटिस अवधि',            placeholder: '30 days' },
  termination_date:      { en: 'Last Working Date',        hi: 'अंतिम कार्य तिथि',      placeholder: 'DD/MM/YYYY' },
  end_date:              { en: 'End Date',                  hi: 'समाप्ति तिथि',          placeholder: 'DD/MM/YYYY' },
  performance_note:      { en: 'Performance Note',         hi: 'प्रदर्शन टिप्पणी',      placeholder: 'Good / Excellent / Satisfactory' },
  father_name:           { en: "Father's Name",            hi: 'पिता का नाम',            placeholder: 'Satish Kumar' },
  address:               { en: 'Full Address',             hi: 'पूर्ण पता',             placeholder: 'House No 5, Village Rampur, District Agra' },
  annual_income:         { en: 'Annual Income (₹)',        hi: 'वार्षिक आय (₹)',         placeholder: '180000' },
  caste_category:        { en: 'Caste / Category',         hi: 'जाति / श्रेणी',         placeholder: 'SC / ST / OBC' },
  years_of_residence:    { en: 'Years of Residence',       hi: 'निवास के वर्ष',         placeholder: '15' },
  head_of_family:        { en: 'Head of Family Name',      hi: 'परिवार के मुखिया का नाम', placeholder: 'Ramesh Kumar' },
  family_members:        { en: 'Family Members',           hi: 'परिवार के सदस्य',       placeholder: 'Wife: Sunita (35), Son: Rahul (10)' },
};
