import PDFDocument from "pdfkit";

export async function generatePDF(
  content: string,
  title: string,
  watermark: boolean = false
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: { top: 60, bottom: 60, left: 70, right: 70 },
    });

    const buffers: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => buffers.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - 140;

    doc.rect(0, 0, doc.page.width, 40).fill("#0A0F1E");
    doc.fillColor("#F5C518").fontSize(14).font("Helvetica-Bold").text("KanoonAI", 70, 12);
    doc.fillColor("#FFFFFF").fontSize(9).font("Helvetica").text("India's AI Legal Document Platform", 140, 14);
    doc.fillColor("#F5C518").fontSize(9).text("kanoonai.in", { align: "right", y: 14 } as any);

    doc.moveDown(2);

    doc.rect(70, 55, pageWidth, 1).fill("#F5C518");

    doc.moveDown(1);

    doc.fillColor("#0A0F1E").fontSize(16).font("Helvetica-Bold").text(title.toUpperCase(), {
      align: "center",
    });

    doc.moveDown(0.5);
    doc.fillColor("#666666").fontSize(9).font("Helvetica").text(
      `Generated on: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })} | Document ID: KAI-${Date.now()}`,
      { align: "center" }
    );

    doc.moveDown(1);
    doc.rect(70, doc.y, pageWidth, 1).fill("#DDDDDD");
    doc.moveDown(1);

    if (watermark) {
      doc.save();
      doc.rotate(45, { origin: [doc.page.width / 2, doc.page.height / 2] });
      doc.fillColor("#CCCCCC").opacity(0.3).fontSize(60).font("Helvetica-Bold").text(
        "PREVIEW",
        doc.page.width / 2 - 150,
        doc.page.height / 2 - 30
      );
      doc.restore();
      doc.opacity(1);
    }

    doc.fillColor("#1A1A2E").fontSize(10).font("Helvetica").lineGap(4);

    const paragraphs = content.split("\n");
    for (const paragraph of paragraphs) {
      const trimmed = paragraph.trim();
      if (!trimmed) {
        doc.moveDown(0.5);
        continue;
      }

      const isHeading = /^[A-Z\s]{5,}:?$/.test(trimmed) || 
                        /^\d+\.\s+[A-Z]/.test(trimmed) ||
                        trimmed.endsWith(":") && trimmed.length < 60;

      if (isHeading) {
        doc.moveDown(0.5);
        doc.fillColor("#0A0F1E").fontSize(11).font("Helvetica-Bold").text(trimmed, { width: pageWidth });
        doc.moveDown(0.2);
        doc.fillColor("#1A1A2E").fontSize(10).font("Helvetica");
      } else {
        doc.text(trimmed, { width: pageWidth, align: "justify" });
        doc.moveDown(0.3);
      }
    }

    doc.moveDown(2);

    const pageHeight = doc.page.height;
    doc.rect(0, pageHeight - 50, doc.page.width, 50).fill("#0A0F1E");
    doc.fillColor("#888888").fontSize(7).font("Helvetica").text(
      "This document was generated by KanoonAI for informational purposes. It is not a substitute for professional legal advice.",
      70,
      pageHeight - 38,
      { width: pageWidth, align: "center" }
    );
    doc.fillColor("#F5C518").fontSize(7).text(
      "© KanoonAI | kanoonai.in",
      { align: "center" }
    );

    doc.end();
  });
}
