import PDFDocument from "pdfkit";

interface PDFOptions {
  watermark?: boolean;
  documentId?: number | string;
  language?: string;
}

const COLORS = {
  navy: "#0A0F1E",
  gold: "#F5C518",
  goldDark: "#B89010",
  text: "#1A1A2E",
  textMuted: "#666666",
  textLight: "#888888",
  border: "#DDDDDD",
  cream: "#F8F4E8",
};

const M = { top: 110, bottom: 90, left: 64, right: 64 };

export async function generatePDF(
  content: string,
  title: string,
  options: PDFOptions | boolean = {}
): Promise<Buffer> {
  // Backwards-compat: old callers passed `watermark` boolean
  const opts: PDFOptions = typeof options === "boolean" ? { watermark: options } : options;
  const watermark = opts.watermark ?? false;
  const docId = `KAI-${opts.documentId ?? Date.now().toString(36).toUpperCase()}`;
  const dateStr = new Date().toLocaleDateString("en-IN", {
    day: "numeric", month: "long", year: "numeric",
  });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margins: M,
      bufferPages: true,
      info: {
        Title: title,
        Author: "KanoonAI",
        Subject: "Legal Document",
        Creator: "KanoonAI - India's AI Legal Document Platform",
        Producer: "KanoonAI",
      },
    });

    const buffers: Buffer[] = [];
    doc.on("data", (c: Buffer) => buffers.push(c));
    doc.on("end", () => resolve(Buffer.concat(buffers)));
    doc.on("error", reject);

    const W = doc.page.width;
    const H = doc.page.height;
    const TW = W - M.left - M.right;

    // ---------- HEADER (drawn on every page) ----------
    const drawHeader = () => {
      doc.save();
      // Navy bar
      doc.rect(0, 0, W, 70).fill(COLORS.navy);
      // Gold accent line
      doc.rect(0, 70, W, 3).fill(COLORS.gold);

      // Logo mark
      doc.rect(M.left, 18, 32, 32).fill(COLORS.gold);
      doc.fillColor(COLORS.navy).fontSize(18).font("Helvetica-Bold")
        .text("K", M.left, 23, { width: 32, align: "center" });

      // Brand name
      doc.fillColor(COLORS.gold).fontSize(16).font("Helvetica-Bold")
        .text("KanoonAI", M.left + 42, 22);
      doc.fillColor("#AAAAAA").fontSize(7.5).font("Helvetica")
        .text("INDIA'S AI LEGAL DOCUMENT PLATFORM", M.left + 42, 42, { characterSpacing: 1.2 });

      // Right side: website + verification
      doc.fillColor(COLORS.gold).fontSize(9).font("Helvetica-Bold")
        .text("kanoonai.in", W - M.right - 100, 22, { width: 100, align: "right" });
      doc.fillColor("#AAAAAA").fontSize(7).font("Helvetica")
        .text(`Verified · ${dateStr}`, W - M.right - 100, 38, { width: 100, align: "right" });
      doc.restore();
    };

    // ---------- FOOTER (drawn on every page) ----------
    const drawFooter = (pageNum: number, totalPages: number) => {
      doc.save();
      // Top gold line of footer
      doc.rect(0, H - 60, W, 1.5).fill(COLORS.gold);
      // Navy bar
      doc.rect(0, H - 58, W, 58).fill(COLORS.navy);

      doc.fillColor("#AAAAAA").fontSize(7).font("Helvetica")
        .text(
          "Generated by KanoonAI · For informational purposes only · Not a substitute for professional legal advice from a licensed advocate.",
          M.left, H - 48,
          { width: TW - 90, align: "left" }
        );

      doc.fillColor(COLORS.gold).fontSize(8).font("Helvetica-Bold")
        .text(`Page ${pageNum} of ${totalPages}`,
          W - M.right - 90, H - 42, { width: 90, align: "right" });

      doc.fillColor("#777777").fontSize(6.5).font("Helvetica")
        .text(`Document ID: ${docId}  ·  © ${new Date().getFullYear()} KanoonAI Technologies Pvt. Ltd.`,
          M.left, H - 22, { width: TW, align: "left" });

      doc.fillColor(COLORS.gold).fontSize(6.5).font("Helvetica-Bold")
        .text("kanoonai.in", W - M.right - 80, H - 22, { width: 80, align: "right" });
      doc.restore();
    };

    // ---------- WATERMARK ----------
    const drawWatermark = (label: string) => {
      doc.save();
      doc.rotate(-35, { origin: [W / 2, H / 2] });
      doc.fillColor("#E0E0E0").opacity(0.25).fontSize(110).font("Helvetica-Bold")
        .text(label, 0, H / 2 - 60, { width: W, align: "center" });
      doc.opacity(1);
      doc.restore();
    };

    // Header for first page
    drawHeader();
    if (watermark) drawWatermark("PREVIEW");

    // ---------- TITLE BLOCK ----------
    let cursorY = M.top - 20;
    doc.rect(M.left, cursorY, TW, 56).fill(COLORS.cream);
    doc.rect(M.left, cursorY, 4, 56).fill(COLORS.gold);
    doc.fillColor(COLORS.navy).fontSize(15).font("Helvetica-Bold")
      .text(title.toUpperCase(), M.left + 18, cursorY + 12, { width: TW - 30 });
    doc.fillColor(COLORS.textMuted).fontSize(8.5).font("Helvetica")
      .text(`Document ID: ${docId}    |    Date: ${dateStr}    |    Jurisdiction: India`,
        M.left + 18, cursorY + 36);

    doc.y = cursorY + 76;
    doc.x = M.left;

    // ---------- BODY CONTENT ----------
    const renderBody = () => {
      doc.fillColor(COLORS.text).fontSize(10).font("Helvetica").lineGap(2.5);

      const lines = content.split("\n");
      for (const raw of lines) {
        const line = raw.trim();
        if (!line) {
          doc.moveDown(0.45);
          continue;
        }

        // Heading detection
        const allCaps = line === line.toUpperCase() && /[A-Z]/.test(line);
        const isMainHeading =
          (allCaps && line.length >= 5 && line.length < 70) ||
          /^(WHEREAS|NOW THEREFORE|IN WITNESS WHEREOF|BETWEEN|AFFIDAVIT|DECLARATION|AGREEMENT)\b/i.test(line);

        const isSubheading =
          /^\d+[\.\)]\s+[A-Z]/.test(line) ||
          /^[A-Z][a-z]+:\s*$/.test(line) ||
          (line.endsWith(":") && line.length < 55 && !line.startsWith("-"));

        const isBullet =
          line.startsWith("•") || line.startsWith("- ") ||
          line.startsWith("* ") || /^[a-z]\)\s/.test(line) ||
          /^\(\w+\)\s/.test(line);

        const isQuote = line.startsWith('"') && line.endsWith('"');

        if (isMainHeading) {
          doc.moveDown(0.5);
          doc.fillColor(COLORS.gold).rect(M.left, doc.y, 30, 1.5).fill();
          doc.moveDown(0.3);
          doc.fillColor(COLORS.navy).fontSize(11).font("Helvetica-Bold")
            .text(line, M.left, doc.y, { width: TW, characterSpacing: 0.5 });
          doc.moveDown(0.3);
          doc.fillColor(COLORS.text).fontSize(10).font("Helvetica").lineGap(2.5);
        } else if (isSubheading) {
          doc.moveDown(0.3);
          doc.fillColor(COLORS.navy).fontSize(10.5).font("Helvetica-Bold")
            .text(line, M.left, doc.y, { width: TW });
          doc.moveDown(0.2);
          doc.fillColor(COLORS.text).fontSize(10).font("Helvetica").lineGap(2.5);
        } else if (isBullet) {
          doc.fillColor(COLORS.text).fontSize(10).font("Helvetica")
            .text(line, M.left + 12, doc.y, { width: TW - 12, align: "left" });
          doc.moveDown(0.2);
        } else if (isQuote) {
          doc.fillColor(COLORS.textMuted).fontSize(10).font("Helvetica-Oblique")
            .text(line, M.left + 16, doc.y, { width: TW - 16 });
          doc.moveDown(0.2);
          doc.fillColor(COLORS.text).font("Helvetica");
        } else {
          doc.fillColor(COLORS.text).fontSize(10).font("Helvetica")
            .text(line, M.left, doc.y, { width: TW, align: "justify" });
          doc.moveDown(0.25);
        }
      }
    };

    renderBody();

    // ---------- SIGNATURE BLOCK ----------
    if (doc.y > H - M.bottom - 200) doc.addPage();
    doc.moveDown(2);

    doc.rect(M.left, doc.y, TW, 1).fill(COLORS.border);
    doc.moveDown(0.8);
    doc.fillColor(COLORS.navy).fontSize(10).font("Helvetica-Bold")
      .text("SIGNATURES", M.left, doc.y, { width: TW });
    doc.moveDown(1.2);

    const colW = (TW - 24) / 2;
    const sigY = doc.y;

    doc.rect(M.left, sigY + 36, colW, 1).fill("#222222");
    doc.fillColor(COLORS.navy).fontSize(8.5).font("Helvetica-Bold")
      .text("PARTY 1", M.left, sigY + 42, { width: colW, align: "center", characterSpacing: 1 });
    doc.fillColor(COLORS.textLight).fontSize(7.5).font("Helvetica")
      .text("Signature, Name & Date", M.left, sigY + 54, { width: colW, align: "center" });

    doc.rect(M.left + colW + 24, sigY + 36, colW, 1).fill("#222222");
    doc.fillColor(COLORS.navy).fontSize(8.5).font("Helvetica-Bold")
      .text("PARTY 2", M.left + colW + 24, sigY + 42, { width: colW, align: "center", characterSpacing: 1 });
    doc.fillColor(COLORS.textLight).fontSize(7.5).font("Helvetica")
      .text("Signature, Name & Date", M.left + colW + 24, sigY + 54, { width: colW, align: "center" });

    doc.y = sigY + 80;

    // Witness section
    doc.moveDown(1.2);
    doc.fillColor(COLORS.navy).fontSize(9).font("Helvetica-Bold")
      .text("WITNESSES:", M.left, doc.y, { width: TW, characterSpacing: 1 });
    doc.moveDown(0.8);
    const wY = doc.y;

    doc.rect(M.left, wY + 30, colW, 1).fill("#444444");
    doc.fillColor(COLORS.textLight).fontSize(7.5).font("Helvetica")
      .text("Witness 1 — Name + Signature", M.left, wY + 36, { width: colW, align: "center" });

    doc.rect(M.left + colW + 24, wY + 30, colW, 1).fill("#444444");
    doc.fillColor(COLORS.textLight).fontSize(7.5).font("Helvetica")
      .text("Witness 2 — Name + Signature", M.left + colW + 24, wY + 36, { width: colW, align: "center" });

    // ---------- DRAW HEADER + FOOTER ON ALL PAGES ----------
    const range = doc.bufferedPageRange();
    const total = range.count;
    for (let i = 0; i < total; i++) {
      doc.switchToPage(range.start + i);
      // Header is already drawn for first page; for others we draw it now
      if (i > 0) drawHeader();
      if (watermark && i > 0) drawWatermark("PREVIEW");
      drawFooter(i + 1, total);
    }

    doc.end();
  });
}
