import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle } from "lucide-react";
import { Link } from "wouter";
import { useSeo } from "@/hooks/use-seo";

const faqs = [
  {
    q: "What is Kanoox AI and how does it work?",
    a: "Kanoox AI is an AI-powered legal document generator built specifically for India. You select a document type (like a Rent Agreement or Partnership Deed), fill in a simple form with your details, and our AI (powered by NVIDIA's world-class language models) instantly generates a professionally drafted, legally-sound document in seconds. No legal knowledge or lawyer required.",
  },
  {
    q: "Are the documents generated by Kanoox AI legally valid in India?",
    a: "Yes, the documents are drafted to comply with applicable Indian laws (e.g., Transfer of Property Act for rent agreements, Indian Contract Act for business contracts). However, Kanoox AI is not a law firm and our documents are AI drafts. For high-stakes matters (property sales, court filings), we recommend having the document reviewed by a registered Advocate.",
  },
  {
    q: "Do I need to pay for every document I generate?",
    a: "Each document has a one-time generation fee ranging from ₹99 to ₹499 depending on complexity. If you generate documents frequently, our subscription plans (Basic ₹299/month or Pro ₹699/month) offer much better value — Basic includes 5 documents/month and Pro includes unlimited documents.",
  },
  {
    q: "How do I pay? What payment methods are supported?",
    a: "We use Razorpay for payments, one of India's most trusted payment gateways. You can pay via UPI (PhonePe, Google Pay, Paytm), credit card, debit card, or net banking. All transactions are encrypted and secure.",
  },
  {
    q: "Can I get a refund if I'm not satisfied?",
    a: "Yes! We offer a 7-day money-back guarantee on all document purchases. If you're not happy with the quality of the generated document for any reason, contact us within 7 days of purchase and we'll issue a full refund — no questions asked. See our Refund Policy for details.",
  },
  {
    q: "In which languages can Kanoox AI generate documents?",
    a: "Kanoox AI can generate documents in English and Hindi. We are working on adding Marathi, Tamil, Telugu, Gujarati, and Kannada. You can select your preferred language when generating a document.",
  },
  {
    q: "Is my personal data and document information secure?",
    a: "Absolutely. All data is encrypted in transit (HTTPS/TLS) and at rest. We do not sell your data to third parties. Your document contents are processed by NVIDIA's enterprise AI API (which does not train on customer data). We comply with India's Digital Personal Data Protection Act (DPDPA) 2023.",
  },
  {
    q: "What document types are available on Kanoox AI?",
    a: "We offer 25+ document types across 6 categories: Rental & Housing (Rent Agreement, Leave & License, NOC, Eviction Notice), Business & Finance (Partnership Deed, MOU, NDA, Business Contract), Personal & Family (Affidavit, Gift Deed, Will), Legal Notices (FIR Draft, Legal Notice, RTI Application), Employment (Offer Letter, Employment Contract, Termination Letter), and Government Applications (Income Certificate, Caste Certificate, Domicile Certificate).",
  },
  {
    q: "How do I download my document after generating it?",
    a: "After generation, you'll see a preview of your document. After completing payment, the full document is unlocked and you can download it as a professionally formatted PDF. You can also re-download it anytime from your Dashboard.",
  },
  {
    q: "Can I edit the generated document after downloading it?",
    a: "Yes! We provide the document as a PDF which you can print and manually fill/sign. For minor edits, you can regenerate the document by adjusting the form fields — each regeneration is included with your purchase. For complete customization, you can also open the PDF in Adobe Acrobat or similar tools.",
  },
];

function FaqItem({ q, a, index }: { q: string; a: string; index: number }) {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04 }}
      className="border border-white/10 rounded-2xl overflow-hidden"
    >
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between p-5 text-left bg-card hover:bg-card/80 transition-colors"
      >
        <span className="text-white font-medium pr-4">{q}</span>
        <ChevronDown className={`h-5 w-5 text-primary flex-shrink-0 transition-transform duration-200 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence>
        {open && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 pt-1 text-muted-foreground text-sm leading-relaxed border-t border-white/5">
              {a}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function FAQ() {
  useSeo({
    title: "FAQ — Frequently Asked Questions about Kanoox AI Legal Documents",
    description: "Get answers about Kanoox AI: how AI generates Indian legal documents, validity, security, payment, refunds, supported languages, and document types.",
  });
  return (
    <div className="min-h-screen bg-background py-20 px-4">
      <div className="max-w-3xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="text-center mb-12">
            <div className="flex justify-center mb-4">
              <div className="h-14 w-14 bg-primary/10 rounded-2xl flex items-center justify-center border border-primary/20">
                <HelpCircle className="h-7 w-7 text-primary" />
              </div>
            </div>
            <h1 className="text-3xl font-bold text-white mb-3">Frequently Asked Questions</h1>
            <p className="text-muted-foreground">Everything you need to know about Kanoox AI</p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <FaqItem key={i} q={faq.q} a={faq.a} index={i} />
            ))}
          </div>

          <div className="mt-12 bg-card border border-white/10 rounded-2xl p-8 text-center">
            <h3 className="text-white font-semibold text-lg mb-2">Still have questions?</h3>
            <p className="text-muted-foreground text-sm mb-4">Our support team is here to help you.</p>
            <Link href="/contact">
              <button className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground rounded-xl font-medium hover:bg-primary/90 transition-colors">
                Contact Us
              </button>
            </Link>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
