import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown, HelpCircle, MessageCircle } from "lucide-react";
import { Link } from "wouter";
import { useSeo } from "@/hooks/use-seo";

const CATEGORIES = [
  {
    label: "General",
    faqs: [
      {
        q: "What is A2z Kanoon AI and how does it work?",
        a: "A2z Kanoon AI is India's most powerful AI-driven legal document generator. You choose a document type (Rent Agreement, NDA, Affidavit, Will, etc.), fill in a short form with your specific details, and our NVIDIA-powered AI instantly writes a complete, professionally drafted, legally compliant document — in under 60 seconds. No legal knowledge required.",
      },
      {
        q: "Are the documents generated by A2z Kanoon AI legally valid in India?",
        a: "Yes. All templates are structured in compliance with Indian statutes: the Indian Contract Act 1872, Transfer of Property Act 1882, Indian Partnership Act 1932, Indian Succession Act 1925, and applicable state Rent Control Acts. They include necessary clauses, witness sections, and stamp duty advisories. For high-stakes matters (property sale, court filings), we recommend getting the final draft reviewed by a licensed Advocate.",
      },
      {
        q: "Do I need a lawyer to use A2z Kanoon AI?",
        a: "No. A2z Kanoon AI is built exactly for situations where hiring a lawyer is overkill — rent agreements, employment offer letters, NDAs, affidavits, RTI applications, and more. For complex litigation or court matters, we always recommend a licensed Advocate. Our Pro Plan includes a 15-minute free consultation for those cases.",
      },
      {
        q: "Who is A2z Kanoon AI built for?",
        a: "A2z Kanoon AI is built for landlords (rental agreements), freelancers & consultants (NDAs, service agreements), small business owners (partnership deeds, MOUs), HR teams (offer letters, employment contracts, termination letters), individuals (affidavits, wills, RTI applications), and anyone in India who needs a professional legal document without waiting days for a lawyer.",
      },
      {
        q: "Which AI model powers A2z Kanoon AI?",
        a: "A2z Kanoon AI uses Meta Llama 3.3 70B served on NVIDIA's enterprise AI platform — one of the highest-ranked large language models on professional writing benchmarks. We generate documents in real-time, streaming the text to your screen as it's written, so you can watch your document come to life.",
      },
    ],
  },
  {
    label: "Documents",
    faqs: [
      {
        q: "What types of legal documents can I create on A2z Kanoon AI?",
        a: "A2z Kanoon AI offers 25+ document types across 6 categories: (1) Rental & Housing — Rent Agreement, Leave & License, NOC, Eviction Notice; (2) Business & Finance — Partnership Deed, MOU, NDA, Business Contract, Invoice; (3) Personal & Family — Affidavit, Gift Deed, Will & Testament, Divorce Petition; (4) Legal Notices — FIR Draft, Legal Notice, Complaint Letter, RTI Application; (5) Employment — Offer Letter, Employment Contract, Experience Certificate, Termination Letter; (6) Government Applications — Income Certificate, Caste Certificate, Domicile Certificate, Ration Card.",
      },
      {
        q: "How do I create a rent agreement online in India?",
        a: "Go to Templates → Rent Agreement. Fill in landlord name, tenant name, property address, monthly rent, security deposit, and duration. A2z Kanoon AI instantly generates a complete Rent Agreement compliant with the applicable state Rent Control Act — including all mandatory clauses, witness section, and stamp duty advisory. You can generate it in English or Hindi.",
      },
      {
        q: "Can I create an affidavit online without a lawyer?",
        a: "Yes. Select 'Affidavit' from the Templates page, enter your details and statement, and our AI drafts a complete Affidavit in the correct legal format per the Indian Evidence Act 1872. The output includes the deponent's declaration, verification clause, and notarization block. Take the printed document to any Notary Public or Oath Commissioner for stamping.",
      },
      {
        q: "How do I write an NDA (Non-Disclosure Agreement) in India?",
        a: "Select 'NDA' on A2z Kanoon AI. Enter the party details, scope of confidential information, duration, and jurisdiction. We generate a bilateral NDA compliant with the Indian Contract Act 1872, including precise definitions, permitted disclosures, exclusions, remedy clauses (injunctive relief), survival period, and Indian court jurisdiction.",
      },
      {
        q: "Can A2z Kanoon AI generate a Will (last will and testament) in India?",
        a: "Yes. Our Will template is structured per the Indian Succession Act 1925. It includes: testator's declaration of sound mind and memory, revocation of prior wills, specific bequests, executor appointment with powers, residuary clause, and the mandatory two-witness attestation block (with the important note that witnesses cannot be beneficiaries). Registration advisory is included.",
      },
      {
        q: "How do I send a legal notice in India?",
        a: "Select 'Legal Notice' on A2z Kanoon AI. Enter the sender/recipient details, facts, legal grounds (relevant IPC or civil law sections are auto-cited by the AI), your specific demand, and response deadline. The notice is formatted as a formal advocate's letterhead letter. Print it, sign it, and send via Registered Post with Acknowledgment Due (RPAD).",
      },
      {
        q: "Can I file an RTI application using A2z Kanoon AI?",
        a: "Yes. The RTI Application template follows the exact format prescribed under the Right to Information Act 2005, Sections 6(1) and 7. Enter the Public Authority (PIO details), specific information you want, and the time period. The AI generates a complete, compliant RTI application. Attach a ₹10 Postal Order or fee as applicable and send to the PIO.",
      },
      {
        q: "Is a partnership deed generated by A2z Kanoon AI legally binding?",
        a: "Yes. Our Partnership Deed template is structured under the Indian Partnership Act 1932 and includes all mandatory clauses: firm name, nature of business, partners' capital contributions, profit/loss sharing ratio, management rights, banking operations, dissolution procedure, and arbitration clause. It is legally enforceable once signed by all partners and witnesses.",
      },
      {
        q: "What is a Leave and License Agreement? How is it different from a Rent Agreement?",
        a: "A Leave and License Agreement grants the licensee permission to use a property for a fixed period without creating a tenancy — making it much easier for the owner to recover possession. It is commonly used in Maharashtra under the Maharashtra Rent Control Act 1999. A Rent Agreement creates tenancy rights which are stronger for the tenant. A2z Kanoon AI generates both formats.",
      },
    ],
  },
  {
    label: "Pricing & Payment",
    faqs: [
      {
        q: "How much does it cost to generate a document on A2z Kanoon AI?",
        a: "Simple documents (Affidavit, NOC, Offer Letter, RTI) start at ₹99. Mid-complexity documents (Rent Agreement, NDA, Legal Notice, Employment Contract) cost ₹199–₹299. Complex documents (Partnership Deed, MOU, Will, Gift Deed, Business Contract) cost ₹499. All prices exclude 18% GST. Drafting and previewing is always free — you pay only to download.",
      },
      {
        q: "What payment methods are accepted?",
        a: "We use Razorpay — India's most trusted payment gateway. Accepted methods: UPI (Google Pay, PhonePe, Paytm, BHIM), Credit Cards (Visa, Mastercard, Amex, Diners), Debit Cards (including RuPay), Net Banking (all major Indian banks), and EMI options for higher-value plans. All transactions are secured with bank-grade encryption.",
      },
      {
        q: "Can I get a refund if I'm not satisfied with my document?",
        a: "Yes — 7-day no-questions-asked refund guarantee on all purchases. If the generated document doesn't meet your needs, email support@kanooxai.in within 7 days with your order ID and we'll process a full refund. Subscription plans can be cancelled anytime; you retain access until the billing cycle ends. See our full Refund Policy for details.",
      },
      {
        q: "What are the subscription plans?",
        a: "Basic Plan (₹299/month): 5 documents per month, priority support, free edits for 7 days, no watermark. Pro Plan (₹699/month): unlimited documents, 15-minute free advocate consultation, API access, white-label PDF output, dedicated account manager. Annual plans available at 30% discount. All plans include full access to all 25+ document types.",
      },
      {
        q: "Is drafting a document free? When do I pay?",
        a: "Absolutely free to draft and preview. Fill in the form, watch the AI write your document live, and read the full preview — all at zero cost. You pay only when you're satisfied and click 'Download PDF'. This means you can see exactly what you're getting before spending a single rupee.",
      },
    ],
  },
  {
    label: "Security & Privacy",
    faqs: [
      {
        q: "Is my personal information secure on A2z Kanoon AI?",
        a: "Yes. All data is encrypted in transit using TLS 1.3 (HTTPS) and encrypted at rest in our database. Your documents are stored securely and are only accessible by your account. We do not sell, rent, or share your data with any third party for marketing purposes. We comply with India's Digital Personal Data Protection Act (DPDPA) 2023.",
      },
      {
        q: "Does A2z Kanoon AI store my documents permanently?",
        a: "Your documents are stored in your account for convenient re-download at any time. You can delete any document from your Dashboard permanently at any time. We retain document data for 90 days after account deletion for legal compliance, after which it is permanently purged from our servers.",
      },
      {
        q: "Does NVIDIA train on my document data?",
        a: "No. A2z Kanoon AI uses NVIDIA's enterprise API, which is subject to enterprise data privacy terms — NVIDIA does not train its models on API customer data. Your document details are transmitted securely to generate the document and are not retained by NVIDIA beyond the API call.",
      },
    ],
  },
  {
    label: "Technical",
    faqs: [
      {
        q: "In which languages can A2z Kanoon AI generate documents?",
        a: "English, Hindi (हिंदी), Marathi (मराठी), Tamil (தமிழ்), and Telugu (తెలుగు). Simply select your preferred language on the document generation page before submitting. Legal terms, names, and section numbers remain in English/Roman script as is standard in Indian legal drafting.",
      },
      {
        q: "How do I download my document after generation?",
        a: "After the AI finishes writing, you see a full preview. Click 'Unlock & Download PDF', complete payment, and the professionally formatted PDF is immediately available for download. You can also re-download any paid document anytime from your Dashboard → My Documents.",
      },
      {
        q: "Can I edit the document after downloading?",
        a: "Yes. Before paying, you can regenerate the document with different inputs at no charge. After downloading, the PDF is yours — open it in Adobe Acrobat, Preview (Mac), or any PDF editor for manual edits. For major changes, simply regenerate on A2z Kanoon AI with the corrected details.",
      },
      {
        q: "What devices and browsers does A2z Kanoon AI work on?",
        a: "A2z Kanoon AI is fully responsive and works on all devices — desktop, tablet, and mobile. It works on all modern browsers: Chrome, Firefox, Safari, and Edge. For the best experience with our live streaming document generation, we recommend Chrome or Edge on desktop.",
      },
      {
        q: "Does A2z Kanoon AI work across all Indian states?",
        a: "Yes. A2z Kanoon AI serves all 28 states and 8 Union Territories of India. Documents are drafted to comply with central Indian laws (Indian Contract Act, Transfer of Property Act, etc.). For state-specific documents (Maharashtra Leave & License, etc.), the AI applies the relevant state law automatically based on the state/city you enter.",
      },
    ],
  },
];

function FaqItem({ q, a, index }: { q: string; a: string; index: number }) {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.025 }}
      className="border border-white/10 rounded-2xl overflow-hidden"
    >
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between p-5 text-left bg-card hover:bg-card/80 transition-colors"
      >
        <span className="text-white font-medium pr-4 text-sm sm:text-base">{q}</span>
        <ChevronDown className={`h-5 w-5 text-primary shrink-0 transition-transform duration-200 ${open ? "rotate-180" : ""}`} />
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.22 }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-5 pt-2 text-muted-foreground text-sm leading-relaxed border-t border-white/5">
              {a}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function FAQ() {
  const [activeCategory, setActiveCategory] = useState("General");

  useSeo({
    title: "FAQ — 30+ Questions About A2z Kanoon AI | Indian Legal Documents Online",
    description: "Everything you need to know about A2z Kanoon AI: how to create rent agreements, NDAs, affidavits, wills, legal notices online in India. Pricing, security, languages, and more.",
  });

  const activeFaqs = CATEGORIES.find((c) => c.label === activeCategory)?.faqs ?? [];

  return (
    <div className="min-h-screen bg-background py-20 px-4">
      <div className="max-w-4xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Header */}
          <div className="text-center mb-12">
            <div className="flex justify-center mb-4">
              <div className="h-14 w-14 bg-primary/10 rounded-2xl flex items-center justify-center border border-primary/20">
                <HelpCircle className="h-7 w-7 text-primary" />
              </div>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3">
              Frequently Asked Questions
            </h1>
            <p className="text-muted-foreground max-w-xl mx-auto">
              30+ answers covering legal document validity, pricing, languages, security, and how to use every document type on A2z Kanoon AI.
            </p>
          </div>

          {/* Category tabs */}
          <div className="flex flex-wrap justify-center gap-2 mb-10">
            {CATEGORIES.map((cat) => (
              <button
                key={cat.label}
                onClick={() => setActiveCategory(cat.label)}
                className={`px-4 py-2 rounded-full text-sm font-medium transition-all ${
                  activeCategory === cat.label
                    ? "bg-primary text-primary-foreground shadow-gold"
                    : "bg-card border border-white/10 text-muted-foreground hover:text-white hover:border-white/30"
                }`}
              >
                {cat.label}
                <span className="ml-1.5 text-xs opacity-70">({CATEGORIES.find(c => c.label === cat.label)?.faqs.length})</span>
              </button>
            ))}
          </div>

          {/* FAQ list */}
          <AnimatePresence mode="wait">
            <motion.div
              key={activeCategory}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              className="space-y-3"
            >
              {activeFaqs.map((faq, i) => (
                <FaqItem key={faq.q} q={faq.q} a={faq.a} index={i} />
              ))}
            </motion.div>
          </AnimatePresence>

          {/* Bottom CTAs */}
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Contact support card */}
            <div className="bg-card border border-white/10 rounded-2xl p-6 text-center flex flex-col items-center">
              <div className="h-12 w-12 bg-primary/10 rounded-2xl border border-primary/20 flex items-center justify-center mb-4">
                <MessageCircle className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-white font-semibold mb-2">Still have questions?</h3>
              <p className="text-muted-foreground text-sm mb-5 max-w-xs mx-auto">
                WhatsApp: Mon–Sat 10 AM – 6 PM IST · Email replies within 24 hours.
              </p>
              <div className="flex flex-col gap-2 w-full">
                <a
                  href="https://wa.me/919876543210"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center justify-center gap-2 px-5 py-2.5 bg-green-500 text-white rounded-xl font-medium hover:bg-green-600 transition-colors text-sm"
                >
                  <MessageCircle className="h-4 w-4" /> Chat on WhatsApp
                </a>
                <Link href="/contact">
                  <button className="w-full inline-flex items-center justify-center gap-2 px-5 py-2.5 bg-card border border-white/15 text-muted-foreground rounded-xl font-medium hover:text-white hover:border-white/30 transition-colors text-sm">
                    Send us an email
                  </button>
                </Link>
              </div>
            </div>

            {/* Try it free card */}
            <div className="bg-gradient-to-br from-primary/10 via-primary/5 to-card border border-primary/20 rounded-2xl p-6 text-center flex flex-col items-center">
              <div className="h-12 w-12 bg-primary/15 rounded-2xl border border-primary/30 flex items-center justify-center mb-4">
                <HelpCircle className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-white font-semibold mb-2">Ready to get started?</h3>
              <p className="text-muted-foreground text-sm mb-5 max-w-xs mx-auto">
                Free to draft & preview. Pay only when you're ready to download your PDF.
              </p>
              <Link href="/documents">
                <button className="inline-flex items-center gap-2 px-6 py-2.5 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-colors shadow-gold text-sm">
                  Browse Templates Free →
                </button>
              </Link>
              <div className="flex items-center gap-4 mt-4 text-xs text-muted-foreground">
                <span>25+ documents</span>
                <span>·</span>
                <span>60 seconds avg</span>
                <span>·</span>
                <span>From ₹99</span>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
