import { motion } from "framer-motion";
import { FileText, ArrowLeft, MessageCircle, Scale } from "lucide-react";
import { Link } from "wouter";
import { useSeo } from "@/hooks/use-seo";

export default function Terms() {
  useSeo({
    title: "Terms of Service — Kanoon AI",
    description: "Read the Kanoon AI Terms of Service governing the use of our AI-powered legal document generation platform.",
  });
  return (
    <div className="min-h-screen bg-background py-16 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Back nav */}
        <Link href="/">
          <div className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-primary transition-colors mb-8 cursor-pointer group">
            <ArrowLeft className="h-4 w-4 group-hover:-translate-x-0.5 transition-transform" />
            Back to Home
          </div>
        </Link>

        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Header */}
          <div className="bg-card border border-white/10 rounded-2xl p-6 mb-8 flex items-start gap-4">
            <div className="h-12 w-12 bg-primary/10 rounded-xl flex items-center justify-center border border-primary/20 shrink-0">
              <Scale className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-white mb-1">Terms of Service</h1>
              <p className="text-muted-foreground text-sm">Last updated: March 1, 2025 · Governed by Indian Law (Mumbai Jurisdiction)</p>
            </div>
          </div>

          <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Kanoon AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. These terms constitute a legally binding agreement between you and Kanoon AI under the laws of India.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
              <p>Kanoon AI is an AI-powered legal document drafting platform that helps Indian users generate, customise, and download legal documents. The Service provides document templates and AI-generated drafts for informational and general use purposes.</p>
              <div className="mt-3 bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-4 text-yellow-200 text-sm">
                <strong>Important Disclaimer:</strong> Kanoon AI is NOT a law firm. Documents generated by our AI are drafts intended as starting points and do not constitute legal advice. For complex legal matters, consult a qualified Advocate registered under the Advocates Act, 1961.
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. Eligibility</h2>
              <p>You must be at least 18 years of age to use Kanoon AI. By creating an account, you represent that you are legally capable of entering into binding contracts under the Indian Contract Act, 1872.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. User Account</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>You are responsible for maintaining the confidentiality of your account</li>
                <li>You must provide accurate information (name, email) during registration</li>
                <li>You are responsible for all activities under your account</li>
                <li>You must notify us immediately of any unauthorized use</li>
                <li>We reserve the right to suspend or terminate accounts that violate these terms</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Payments & Pricing</h2>
              <ul className="list-disc pl-6 space-y-1">
                <li>Document generation fees are as displayed on the platform (₹99–₹499 per document)</li>
                <li>All prices are inclusive of applicable GST</li>
                <li>Payments are processed by Razorpay, a PCI-DSS compliant payment gateway</li>
                <li>We accept UPI, credit cards, debit cards, and net banking</li>
                <li>Subscription plans renew automatically unless cancelled 24 hours before the renewal date</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Prohibited Uses</h2>
              <p>You agree NOT to use Kanoon AI to:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Generate fraudulent, forged, or illegal documents</li>
                <li>Misrepresent facts in legal documents</li>
                <li>Violate any applicable Indian or international law</li>
                <li>Infringe on any third party's intellectual property rights</li>
                <li>Attempt to reverse-engineer, scrape, or copy our AI systems</li>
                <li>Create documents for the purpose of money laundering or financial fraud</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
              <p>You retain ownership of the information you submit. By using the Service, you grant Kanoon AI a limited licence to process your data for document generation. The AI-generated document content, once downloaded, belongs to you. Kanoon AI's platform, branding, software, and proprietary AI prompts remain our intellectual property.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
              <p>To the maximum extent permitted under Indian law, Kanoon AI shall not be liable for:</p>
              <ul className="list-disc pl-6 mt-2 space-y-1">
                <li>Legal outcomes arising from use of generated documents</li>
                <li>Errors or inaccuracies in AI-generated content</li>
                <li>Loss of data, profits, or business</li>
                <li>Indirect, incidental, or consequential damages</li>
              </ul>
              <p className="mt-2">Our total aggregate liability shall not exceed the amount you paid us in the preceding 3 months.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">9. Governing Law & Dispute Resolution</h2>
              <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts in Mumbai, Maharashtra. For consumer disputes, you may also approach the appropriate consumer forum under the Consumer Protection Act, 2019.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">10. Contact</h2>
              <p>For any questions about these Terms, contact us at <strong className="text-primary">legal@kanooxai.in</strong></p>
            </section>
          </div>

          {/* Bottom CTA */}
          <div className="mt-12 bg-card border border-white/10 rounded-2xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <h3 className="text-white font-semibold mb-1">Questions about our Terms?</h3>
              <p className="text-muted-foreground text-sm">Email <span className="text-primary">legal@kanooxai.in</span> — we respond within 2 business days.</p>
            </div>
            <div className="flex gap-2 shrink-0">
              <Link href="/contact">
                <button className="flex items-center gap-2 px-4 py-2.5 bg-primary text-primary-foreground rounded-xl text-sm font-medium hover:bg-primary/90 transition-colors">
                  <MessageCircle className="h-4 w-4" /> Contact Us
                </button>
              </Link>
              <Link href="/documents">
                <button className="flex items-center gap-2 px-4 py-2.5 bg-card border border-white/15 text-muted-foreground rounded-xl text-sm font-medium hover:text-white transition-colors">
                  <FileText className="h-4 w-4" /> Browse Templates
                </button>
              </Link>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
