// Placeholder — replaced by the real serverless bundle during `vercel build`
// (generated by artifacts/api-server/build.mjs -> api/index.mjs).
// If this handler ever runs in production, the build did not generate the bundle.
export const config = {
  api: { bodyParser: false },
  maxDuration: 300,
};

export default function handler(_req, res) {
  res.statusCode = 500;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ error: "API bundle was not generated during build." }));
}
